tab_aimant_sort = [
    {
        "id": "S1",
        "number":3,
        "description": "Take 1 card in the shop for free",
        "achat": 30,
        "vente": 25,
    },
    {
        "id": "S2",
        "number":3,
        "description": "+1 strength",
        "achat": 10,
        "vente": 5,
    },
    {
        "id": "S3",
        "number":3,
        "description": "+4 toughness",
        "achat": 10,
        "vente": 5,
    },
    {
        "id": "S4",
        "number":5,
        "description": "Search in the deck for an Ekip from a set you already possess and shuffle.",
        "achat": 15,
        "vente": 10,
    },
    {
        "id": "S5",
        "description": "Renew the shop.",
        "number":4,
        "achat": 20,
        "vente": 15,
    },
    {
        "id": "S6",
        "description": "+ 3 coins",
        "number":1,
        "achat": 0,
        "vente": 0,
    },
    {
        "id": "S7",
        "description": "+ 4 coins",
        "number":1,
        "achat": 0,
        "vente": 0,
    },
    {
        "id": "S8",
        "description": "+ 6 coins",
        "number":1,
        "achat": 0,
        "vente": 0,
    },
    {
        "id": "S9",
        "description": "+ 9 coins",
        "number":1,
        "achat": 0,
        "vente": 0,
    },
    {
        "id": "S10",
        "description": "+ 12 coins",
        "number":1,
        "achat": 0,
        "vente": 0,
    },
    {
        "id": "S11",
        "description": "+ 15 coins",
        "number":1,
        "achat": 0,
        "vente": 0,
    },
    {
        "id": "S12",
        "description": "Destroy an aimant",
        "number":2,
        "achat": 40,
        "vente": 35,
    },
    {
        "id": "A1",
        "description": "If you play no card during your turn draw 2 cards",
        "number":1,
        "achat": 25,
        "vente": 30,
    },
    {
        "id": "A2",
        "description": "Change the type of a 'THON",
        "number":2,
        "achat": 45,
        "vente": 40,
    },
    {
        "id": "A3",
        "description": "+ 1 coins per turn.",
        "number":1,
        "achat": 10,
        "vente": 5,
    },
    {
        "id": "A3",
        "description": "+ 2 coins per turn.",
        "number":1,
        "achat": 15,
        "vente": 10,
    },
    {
        "id": "A4",
        "description": "+ 3 coins per turn.",
        "number":1,
        "achat": 20,
        "vente": 15,
    },
    {
        "id": "A5",
        "description": "+ 4 coins per turn.",
        "number":1,
        "achat": 25,
        "vente": 20,
    },
    {
        "id": "A6",
        "description": "+ 5 coins per turn.",
        "number":1,
        "achat": 30,
        "vente": 25,
    },
    {
        "id": "A7",
        "description": "Draw 1 more card each turn",
        "number":1,
        "achat": 35,
        "vente": 30,
    },
];