tab_ekip = [
    {
        "id": "E1",
        "description": "Marker cone",
        "type": "Plastic",
        "part": "Body",
        "achat": 20,
        "vente": 15,
    },
    {
        "id": "E2",
        "description": "Folded traffic sign",
        "type": "Plastic",
        "part": "Right_Leg",
        "achat": 20,
        "vente": 15,
    },
    {
        "id": "E3",
        "description": "Folded traffic sign",
        "type": "Plastic",
        "part": "Left_Leg",
        "achat": 20,
        "vente": 15,
    },
    {
        "id": "E4",
        "description": "Party hat",
        "type": "Plastic",
        "part": "Hat",
        "achat": 20,
        "vente": 15,
    },
    {
        "id": "E5",
        "description": "Neon Arm",
        "type": "Plastic",
        "part": "Right_Arm",
        "achat": 20,
        "vente": 15,
    },
    {
        "id": "E6",
        "description": "Neon Arm",
        "type": "Plastic",
        "part": "Left_Arm",
        "achat": 20,
        "vente": 15,
    },
    {
        "id": "E7",
        "description": "Anti-covid mask",
        "type": "Plastic",
        "part": "Accessory",
        "achat": 20,
        "vente": 15,
    },
    {
        "id": "E8",
        "description": "Marcel",
        "type": "Fire",
        "part": "Body",
        "achat": 20,
        "vente": 15,
    },
    {
        "id": "E9",
        "description": "Tourist cap",
        "type": "Fire",
        "part": "Hat",
        "achat": 20,
        "vente": 15,
    },
    {
        "id": "E10",
        "description": "Sunglasses",
        "type": "Fire",
        "part": "Accessory",
        "achat": 20,
        "vente": 15,
    },
    {
        "id": "E11",
        "description": "Sunburned arm",
        "type": "Fire",
        "part": "Right_Arm",
        "achat": 20,
        "vente": 15,
    },
    {
        "id": "E12",
        "description": "Sunburned arm",
        "type": "Fire",
        "part": "Left_Arm",
        "achat": 20,
        "vente": 15,
    },
    {
        "id": "E13",
        "description": "Crocs and high socks",
        "type": "Fire",
        "part": "Left_Leg",
        "achat": 20,
        "vente": 15,
    },
    {
        "id": "E14",
        "description": "Crocs and high socks",
        "type": "Fire",
        "part": "Right_Leg",
        "achat": 20,
        "vente": 15,
    },
    {
        "id": "E15",
        "description": "Water bottle",
        "type": "Water",
        "part": "Body",
        "achat": 20,
        "vente": 15,
    },
    {
        "id": "E16",
        "description": "Shark head",
        "type": "Water",
        "part": "Hat",
        "achat": 20,
        "vente": 15,
    },
    {
        "id": "E17",
        "description": "Fin",
        "type": "Water",
        "part": "Accessory",
        "achat": 20,
        "vente": 15,
    },
    {
        "id": "E18",
        "description": "Water gun",
        "type": "Water",
        "part": "Right_Arm",
        "achat": 20,
        "vente": 15,
    },
    {
        "id": "E19",
        "description": "Water gun",
        "type": "Water",
        "part": "Left_Arm",
        "achat": 20,
        "vente": 15,
    },
    {
        "id": "E20",
        "description": "Webbed foot",
        "type": "Water",
        "part": "Left_Leg",
        "achat": 20,
        "vente": 15,
    },
    {
        "id": "E21",
        "description": "Webbed foot",
        "type": "Water",
        "part": "Right_Leg",
        "achat": 20,
        "vente": 15,
    },
    {
        "id": "E22",
        "description": "Battery",
        "type": "Electric",
        "part": "Body",
        "achat": 20,
        "vente": 15,
    },
    {
        "id": "E23",
        "description": "Antenna with power meter",
        "type": "Electric",
        "part": "Hat",
        "achat": 20,
        "vente": 15,
    },
    {
        "id": "E24",
        "description": "Electronic bracelet",
        "type": "Electric",
        "part": "Accessory",
        "achat": 20,
        "vente": 15,
    },
    {
        "id": "E25",
        "description": "Taser",
        "type": "Electric",
        "part": "Right_Arm",
        "achat": 20,
        "vente": 15,
    },
    {
        "id": "E26",
        "description": "Taser",
        "type": "Electric",
        "part": "Left_Arm",
        "achat": 20,
        "vente": 15,
    },
    {
        "id": "E27",
        "description": "Charging cable",
        "type": "Electric",
        "part": "Left_Leg",
        "achat": 20,
        "vente": 15,
    },
    {
        "id": "E28",
        "description": "Charging cable",
        "type": "Electric",
        "part": "Right_Leg",
        "achat": 20,
        "vente": 15,
    },
];